version: 2
jobs: #pipline
  build: #pierwszy musi byc bild

    working_directory: ~/cicd # ciezka do projektu

    docker: #stawia niezalezne srodowisko
    - image: circleci/openjdk:8u171-jdk
      environment:
        JDBC_DATABASE_URL: jdbc:postgresql://127.0.0.1/testdb
        JDBC_DATABASE_USERNAME: root
        JDBC_DATABASE_PASSWORD: root


    - image: circleci/postgres:9.6.5-alpine-ram
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: testdb


    steps: #kroki
    - checkout #pobieranie

    - run: mvn dependency:go-offline #zaciaganie zaleznosci
    - run: mvn test # testy w java

  deploy:
    docker:
    - image: buildpack-deps:trusty

    steps:
    - checkout
    - run:
        name: Deploying app to heroku
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master


workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build